In [2]:
import numpy as np

# Quelques fonctions utiles

On a créé un tableau 2D `rdm_mat` contenant des valeurs aléatoires. 

In [5]:
rdm_mat = np.random.rand(3,2)

[[0.34228456 0.23091289]
 [0.03434003 0.36161667]
 [0.12585125 0.67850125]]


Donner le type de la variable rdm_mat

In [60]:
type = np.dtype(rdm_mat)

TypeError: data type not understood

Donner la somme des éléments de ce tableau 2D

In [8]:
np.sum(rdm_mat)

1.7735066376268769

Faire en sorte de récupérer la valeur maximale sur chaque ligne (sans boucles) avec la fonction np.max

In [10]:
rdm_mat.max(1)

array([0.34228456, 0.36161667, 0.67850125])

Faire de même pour récupérer la valeur maximum pour chaque colonne (sans boucles)

In [11]:
rdm_mat.min(0)

array([0.03434003, 0.23091289])

Faire la même chose (max des lignes) en définissant un tableau avec une boucle for et la fonction max de numpy

On crée un vecteur aléatoire de taille 100 `rdm_vect`

In [16]:
rdm_vect = np.random.randn(100)
rdm_vect.shape

(100,)

Récupérer la position de la valeur maximale du vecteur avec la méthode np.argmax

In [19]:
x = np.argmax(rdm_vect)

35

Afficher cette valeur 

Convertir le vecteur en un tableau 10, 10

In [48]:
new_arr = rdm_vect.reshape(10, 10)
new_arr

array([[ 0.19882803, -0.45207917,  0.18314263, -0.87023707, -0.021266  ,
        -2.33762172, -0.82533695,  0.5065655 , -0.13085242,  1.89007397],
       [-0.59736021, -0.97342401, -1.35151114, -0.409714  , -0.65178029,
        -1.1229262 , -0.89749434, -2.12520059, -1.41879299, -0.52970554],
       [-0.10260244, -1.0895765 , -0.52835035,  1.48042417, -0.68140302,
         0.74576015, -0.07282305,  0.96568176,  0.76451648,  0.38067923],
       [-0.05992952,  1.14462067, -0.99970911,  0.55807523, -0.12181077,
         2.85610815,  1.13945902,  0.20928389,  0.22741282,  1.64561781],
       [-0.34013971, -0.47894342,  0.24527663,  1.77525531,  0.32447827,
         1.44272021, -1.65608496,  0.08823154, -0.40930923,  1.37053834],
       [-1.58457503,  1.33018059,  0.93492131,  0.35650325, -0.76374971,
        -0.68368021, -2.46329366, -1.99660944, -0.4040362 , -0.02377098],
       [ 0.59046574,  0.43074935, -0.74635406, -1.88652432, -0.21200028,
        -0.65158182,  1.65561563, -1.28850921

Calculer la moyenne de chaque ligne de ce tableau (sans boucles)

In [57]:
mean_arr = new_arr.mean(0)
mean_arr

array([-0.4671794 , -0.04804058, -0.31209914,  0.07854529, -0.46433156,
       -0.07446129, -0.47114613, -0.72586709,  0.04316555,  0.4792249 ])

Faire un tableau qui contient la moyenne de chaque colonne du tableau 

Calculer la somme de chaque colonne (sans boucles)

In [62]:
sum_arr = new_arr.sum(1)
sum_arr

array([ -1.85878321, -10.07790932,   1.86230644,   6.59912819,
         2.36202298,  -5.29811008,  -2.33380114,   1.42254849,
        -5.67486613,  -6.6244305 ])

Calculer la somme pour chaque ligne (sans boucles)

In [63]:
sum_arr = new_arr.sum(0)
sum_arr

array([-4.67179397, -0.48040577, -3.12099138,  0.78545293, -4.64331556,
       -0.74461295, -4.71146126, -7.25867087,  0.43165551,  4.79224904])